### PR TITLE
UI updates, Contract call hooks clean up.

### LINKED ISSUE #46: Dynamic connector name
**Describe the bug**
When you connect your wallet(any wallet), it uses the default metamask information(wallet name and information). 

**To Reproduce**

1. Connect your wallet.

**Expected behavior**
When connected to wallet, it should show the connected wallet's name and logo

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by njokuScript**
# Description
This pull request implements new UI updates which uses L1 address to fetch token information.

- Fix github connection error
- Use L1 token contract to read data
- Clean up and bug fixes
- Extra data validation on Input

Screen Shot 2024-03-25 at 8 09 12 PM

# Issues

Fixes #46 #45 
Refs #

# Checklist:

- [x] 1 PR, 1 purpose: my Pull Request applies to a single purpose
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have updated the docs to reflect my changes if applicable
- [ ] I have added tests (and stories for frontend components) that prove my fix is effective or that my feature works
- [x] I have performed a self-review of my own code
- [x] If my code involves visual changes, I am adding applicable screenshots to this thread

### CODE REVIEW

File: base-migrate-app/src/app/home/connect-github.tsx [hunk 1]
```diff
@@ -33,7 +33,7 @@ const ConnectGithub = () => {
 
   const url = !cookies?.isAuthenticated
     ? 'https://github.com/apps/base-migrate/installations/new'
-    : 'https://github.com/login/oauth/authorize?client_id=Iv1.c178abebc418bb02&scope=repo&redirect_url=http://localhost:3000/home';
+    : 'https://github.com/login/oauth/authorize?client_id=Iv1.c178abebc418bb02&scope=repo&redirect_uri=http://localhost:3000/home';
```
Comment (MeisterJustice) [inline base-migrate-app/src/app/home/connect-github.tsx:37]: update redirect_url to live

**Review by MeisterJustice — CHANGES_REQUESTED** [review]
